USE [GdprCore21]
GO

ALTER TABLE [dbo].[GdprRPD]  WITH CHECK ADD  CONSTRAINT [FK_GdprRPD_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[GdprRPD] CHECK CONSTRAINT [FK_GdprRPD_UserId]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprRPD_UserId] ON [dbo].[GdprRPD] ([UserId])
GO

