CREATE TABLE [dbo].[GdprTest]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprTest_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [NINumber] NVARCHAR(MAX) NULL,
    [Created] DATETIME2 CONSTRAINT [DF_GdprTest_Created] DEFAULT SYSUTCDATETIME() NOT NULL,  
    [LastUpdate] DATETIME2 NULL, 
    [NextUpdate] DATETIME2 NULL, 
    [Source] NVARCHAR(MAX) NULL 
)
GO;
CREATE UNIQUE CLUSTERED INDEX [IX_GdprTest_Created] ON [dbo].[GdprTest] ([Created])
GO;
