CREATE TABLE [dbo].[GdprPDS]
(
    [Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprPDS_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [TableName] NVARCHAR(50) NULL, 
    [FieldName] NVARCHAR(50) NULL, 
    [Status] INT CONSTRAINT [DF_GdprPDS_Status] DEFAULT 0 NOT NULL, 
    [UserUpdateFlag] INT CONSTRAINT [DF_GdprPDS_UserUpdateFlag] DEFAULT 0 NOT NULL, 
    [DisplayName] NVARCHAR(50) NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Sources] NVARCHAR(MAX) NULL, 
    [StorageProtection] NVARCHAR(MAX) NULL, 
    [StorageArchiving] NVARCHAR(MAX) NULL, 
    [StorageDur] INT NULL, 
    [StorageJustification] NVARCHAR(MAX) NULL,
    [Created] DATETIME2 CONSTRAINT [DF_GdprPDS_Created] DEFAULT GETUTCDATE() NOT NULL, 
    [DtdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprPDS_DtdId] FOREIGN KEY REFERENCES [dbo].[GdprDTD] (Id) ON DELETE CASCADE NOT NULL, 
    [DcdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprPDS_DcdId] FOREIGN KEY REFERENCES [dbo].[GdprDCD] (Id) ON DELETE CASCADE NOT NULL, 
)
GO;
CREATE UNIQUE CLUSTERED INDEX [IX_GdprPDS_Created] ON [dbo].[GdprPDS] ([Created])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprPDS_DtdId] ON [dbo].[GdprPDS] ([DtdId])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprCXP_DcdId] ON [dbo].[GdprPDS] ([DcdId])
GO;

