CREATE TABLE [dbo].[GdprDCD]
(
    [Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprDCD_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [DisplayName] NVARCHAR(50) NULL, 
    [Details] NVARCHAR(MAX) NULL
)
