CREATE TABLE [dbo].[GdprURD]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprURD_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [Name] NVARCHAR(50) NULL, 
    [RoleCode] INT CONSTRAINT [DF_GdprURP_RoleCode] DEFAULT 0 NOT NULL, 
    [Status] INT CONSTRAINT [DF_GdprURP_Status] DEFAULT 0 NOT NULL, 
    [Purpose] NVARCHAR(MAX) NULL, 
    [Description] NVARCHAR(MAX) NULL
)
