CREATE TABLE [dbo].[GdprRPD]
(
    [Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprRPD_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [FullName] NVARCHAR(MAX) NULL, 
    [Email] NVARCHAR(256) NOT NULL, 
    [ChildFlag] INT CONSTRAINT [DF_GdprRPD_ChildFlag] DEFAULT 0 NOT NULL, 
    [StopComms] INT CONSTRAINT [DF_GdprRPD_StopComms] DEFAULT 0 NOT NULL , 
    [RestrictProc] INT CONSTRAINT [DF_GdprRPD_RestrictProc] DEFAULT 0 NOT NULL, 
    [LoginCount] INT CONSTRAINT [DF_GdprRPD_LoginCount] DEFAULT 0 NOT NULL,
    [LastLogin] DATETIME2 NULL, 
    [AccountDeleted] DATETIME2 NULL, 
    [UpdateFlag] INT CONSTRAINT [DF_GdprRPD_UpdateFlag] DEFAULT 0 NOT NULL, 
    [NotificationURL] NVARCHAR(MAX) NULL, 
    [UserId] NVARCHAR(450) NULL, 
    [UrdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprRPD_UrdId]  FOREIGN KEY REFERENCES [dbo].[GdprURD] (Id) ON DELETE CASCADE  NOT NULL, 
    [Created] DATETIME2 CONSTRAINT [DF_GdprRPD_Created] DEFAULT SYSUTCDATETIME() NOT NULL,  
    [LastUpdate] DATETIME2 NULL, 
    [NextUpdate] DATETIME2 NULL, 
    [Source] NVARCHAR(MAX) NULL 
)
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprRPD_UrdId] ON [dbo].[GdprRPD] ([UrdId])
GO;
CREATE UNIQUE CLUSTERED INDEX [IX_GdprRPD_Email] ON [dbo].[GdprRPD] ([Email])
GO;

