CREATE TABLE [dbo].[GdprCXP]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprCXP_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [ConsentCode] INT CONSTRAINT [DF_GdprCXP_ConsentCode] DEFAULT 0 NOT NULL, 
    [Granted] DATETIME2 CONSTRAINT [DF_GdprCXP_Granted] DEFAULT SYSUTCDATETIME() NOT NULL, 
    [Revoked] DATETIME2 NULL, 
    [FpdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprCXP_FpdId]  FOREIGN KEY REFERENCES [dbo].[GdprFPD] (Id) ON DELETE CASCADE  NOT NULL, 
    [RpdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprCXP_RpdId]  FOREIGN KEY REFERENCES [dbo].[GdprRPD] (Id) ON DELETE CASCADE  NOT NULL, 
)
GO;
CREATE UNIQUE CLUSTERED INDEX [IX_GdprCXP_Granted] ON [dbo].[GdprCXP] ([Granted])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprCXP_FpdId] ON [dbo].[GdprCXP] ([FpdId])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprCXP_RpdId] ON [dbo].[GdprCXP] ([RpdId])
GO;
