/*
Deployment script for GdprCore21

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "GdprCore21"
:setvar DefaultFilePrefix "GdprCore21"
:setvar DefaultDataPath "C:\Users\wills\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB"
:setvar DefaultLogPath "C:\Users\wills\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[GdprCXP]...';


GO
CREATE TABLE [dbo].[GdprCXP] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [ConsentCode] INT              NOT NULL,
    [Granted]     DATETIME2 (7)    NOT NULL,
    [Revoked]     DATETIME2 (7)    NULL,
    [FpdId]       UNIQUEIDENTIFIER NOT NULL,
    [RpdId]       UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprCXP].[IX_GdprCXP_Granted]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprCXP_Granted]
    ON [dbo].[GdprCXP]([Granted] ASC);


GO
PRINT N'Creating [dbo].[GdprCXP].[IX_GdprCXP_FpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprCXP_FpdId]
    ON [dbo].[GdprCXP]([FpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprCXP].[IX_GdprCXP_RpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprCXP_RpdId]
    ON [dbo].[GdprCXP]([RpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprDCD]...';


GO
CREATE TABLE [dbo].[GdprDCD] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [DisplayName] NVARCHAR (40)    NOT NULL,
    [Details]     NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprDCD].[IX_GdprDCD_DisplayName]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprDCD_DisplayName]
    ON [dbo].[GdprDCD]([DisplayName] ASC);


GO
PRINT N'Creating [dbo].[GdprDTD]...';


GO
CREATE TABLE [dbo].[GdprDTD] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [DisplayName] NVARCHAR (40)    NOT NULL,
    [Details]     NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprDTD].[IX_GdprDTD_DisplayName]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprDTD_DisplayName]
    ON [dbo].[GdprDTD]([DisplayName] ASC);


GO
PRINT N'Creating [dbo].[GdprDXP]...';


GO
CREATE TABLE [dbo].[GdprDXP] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [ProcFlags] INT              NOT NULL,
    [FpdId]     UNIQUEIDENTIFIER NOT NULL,
    [PdsId]     UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprDXP].[IX_GdprDXP_FpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprDXP_FpdId]
    ON [dbo].[GdprDXP]([FpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprDXP].[IX_GdprDXP_RpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprDXP_RpdId]
    ON [dbo].[GdprDXP]([PdsId] ASC);


GO
PRINT N'Creating [dbo].[GdprEDT]...';


GO
CREATE TABLE [dbo].[GdprEDT] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [Name]         NVARCHAR (80)    NOT NULL,
    [Address]      NVARCHAR (MAX)   NULL,
    [Country]      NVARCHAR (40)    NULL,
    [Details]      NVARCHAR (MAX)   NULL,
    [TransferFlag] INT              NOT NULL,
    [FpdId]        UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprEDT].[IX_GdprEDT_Name]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprEDT_Name]
    ON [dbo].[GdprEDT]([Name] ASC);


GO
PRINT N'Creating [dbo].[GdprEDT].[IX_GdprEDT_FpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprEDT_FpdId]
    ON [dbo].[GdprEDT]([FpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprFPD]...';


GO
CREATE TABLE [dbo].[GdprFPD] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [Name]              NVARCHAR (40)    NOT NULL,
    [ProcessingBasis]   NVARCHAR (MAX)   NULL,
    [ProcessingPurpose] NVARCHAR (MAX)   NULL,
    [ConsentRefusal]    NVARCHAR (MAX)   NULL,
    [ConsentCode]       INT              NOT NULL,
    [Status]            INT              NOT NULL,
    [ProcFlag]          INT              NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprFPD].[IX_GdprFPD_Name]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprFPD_Name]
    ON [dbo].[GdprFPD]([Name] ASC);


GO
PRINT N'Creating [dbo].[GdprPDF]...';


GO
CREATE TABLE [dbo].[GdprPDF] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [TableName]   NVARCHAR (128)   NULL,
    [FieldName]   NVARCHAR (128)   NULL,
    [Value]       INT              NOT NULL,
    [Combine]     INT              NOT NULL,
    [Description] NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([Value] ASC)
);


GO
PRINT N'Creating [dbo].[GdprPDS]...';


GO
CREATE TABLE [dbo].[GdprPDS] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [TableName]            NVARCHAR (128)   NULL,
    [FieldName]            NVARCHAR (128)   NULL,
    [Status]               INT              NOT NULL,
    [UserUpdateFlag]       INT              NOT NULL,
    [DisplayName]          NVARCHAR (40)    NOT NULL,
    [Description]          NVARCHAR (MAX)   NULL,
    [Sources]              NVARCHAR (MAX)   NULL,
    [StorageProtection]    NVARCHAR (MAX)   NULL,
    [StorageArchiving]     NVARCHAR (MAX)   NULL,
    [StorageDur]           INT              NULL,
    [StorageJustification] NVARCHAR (MAX)   NULL,
    [Created]              DATETIME2 (7)    NOT NULL,
    [DtdId]                UNIQUEIDENTIFIER NOT NULL,
    [DcdId]                UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprPDS].[IX_GdprPDS_Name]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprPDS_Name]
    ON [dbo].[GdprPDS]([DisplayName] ASC);


GO
PRINT N'Creating [dbo].[GdprPDS].[IX_GdprPDS_DtdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprPDS_DtdId]
    ON [dbo].[GdprPDS]([DtdId] ASC);


GO
PRINT N'Creating [dbo].[GdprPDS].[IX_GdprPDS_DcdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprPDS_DcdId]
    ON [dbo].[GdprPDS]([DcdId] ASC);


GO
PRINT N'Creating [dbo].[GdprRPD]...';


GO
CREATE TABLE [dbo].[GdprRPD] (
    [Id]              UNIQUEIDENTIFIER NOT NULL,
    [FullName]        NVARCHAR (MAX)   NULL,
    [Email]           NVARCHAR (256)   NOT NULL,
    [ChildFlag]       INT              NOT NULL,
    [StopComms]       INT              NOT NULL,
    [RestrictProc]    INT              NOT NULL,
    [LoginCount]      INT              NOT NULL,
    [LastLogin]       DATETIME2 (7)    NULL,
    [AccountDeleted]  DATETIME2 (7)    NULL,
    [UpdateFlag]      INT              NOT NULL,
    [NotificationURL] NVARCHAR (MAX)   NULL,
    [UserId]          NVARCHAR (450)   NULL,
    [UrdId]           UNIQUEIDENTIFIER NOT NULL,
    [Created]         DATETIME2 (7)    NOT NULL,
    [LastUpdate]      DATETIME2 (7)    NULL,
    [NextUpdate]      DATETIME2 (7)    NULL,
    [Source]          NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprRPD].[IX_GdprRPD_Email]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprRPD_Email]
    ON [dbo].[GdprRPD]([Email] ASC);


GO
PRINT N'Creating [dbo].[GdprRPD].[IX_GdprRPD_UrdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprRPD_UrdId]
    ON [dbo].[GdprRPD]([UrdId] ASC);


GO
PRINT N'Creating [dbo].[GdprRXP]...';


GO
CREATE TABLE [dbo].[GdprRXP] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [ProcFlags] INT              NOT NULL,
    [FpdId]     UNIQUEIDENTIFIER NOT NULL,
    [UrdId]     UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprRXP].[IX_GdprRXP_FpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprRXP_FpdId]
    ON [dbo].[GdprRXP]([FpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprRXP].[IX_GdprRXP_UrdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprRXP_UrdId]
    ON [dbo].[GdprRXP]([UrdId] ASC);


GO
PRINT N'Creating [dbo].[GdprTest]...';


GO
CREATE TABLE [dbo].[GdprTest] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [NINumber]   NVARCHAR (MAX)   NULL,
    [Created]    DATETIME2 (7)    NOT NULL,
    [LastUpdate] DATETIME2 (7)    NULL,
    [NextUpdate] DATETIME2 (7)    NULL,
    [Source]     NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprTest].[IX_GdprTest_Created]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprTest_Created]
    ON [dbo].[GdprTest]([Created] ASC);


GO
PRINT N'Creating [dbo].[GdprURD]...';


GO
CREATE TABLE [dbo].[GdprURD] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [Name]        NVARCHAR (40)    NOT NULL,
    [RoleCode]    INT              NOT NULL,
    [Status]      INT              NOT NULL,
    [Purpose]     NVARCHAR (MAX)   NULL,
    [Description] NVARCHAR (MAX)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprURD].[IX_GdprURD_Name]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprURD_Name]
    ON [dbo].[GdprURD]([Name] ASC);


GO
PRINT N'Creating [dbo].[GdprUTA]...';


GO
CREATE TABLE [dbo].[GdprUTA] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [Accepted] DATETIME2 (7)    NOT NULL,
    [Revoked]  DATETIME2 (7)    NULL,
    [RpdId]    UNIQUEIDENTIFIER NOT NULL,
    [WstId]    UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprUTA].[IX_GdprUTA_Created]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprUTA_Created]
    ON [dbo].[GdprUTA]([Accepted] ASC);


GO
PRINT N'Creating [dbo].[GdprUTA].[IX_GdprUTA_RpdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprUTA_RpdId]
    ON [dbo].[GdprUTA]([RpdId] ASC);


GO
PRINT N'Creating [dbo].[GdprUTA].[IX_GdprUTA_WstId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprUTA_WstId]
    ON [dbo].[GdprUTA]([WstId] ASC);


GO
PRINT N'Creating [dbo].[GdprWST]...';


GO
CREATE TABLE [dbo].[GdprWST] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [Title]       NVARCHAR (80)    NOT NULL,
    [Description] NVARCHAR (MAX)   NULL,
    [Created]     DATETIME2 (7)    NOT NULL,
    [Published]   DATETIME2 (7)    NULL,
    [Updated]     DATETIME2 (7)    NULL,
    [Status]      INT              NOT NULL,
    [Link]        NVARCHAR (MAX)   NULL,
    [Hash]        NVARCHAR (250)   NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprWST].[IX_GdprWST_Title]...';


GO
CREATE UNIQUE CLUSTERED INDEX [IX_GdprWST_Title]
    ON [dbo].[GdprWST]([Title] ASC);


GO
PRINT N'Creating [dbo].[GdprWXR]...';


GO
CREATE TABLE [dbo].[GdprWXR] (
    [Id]    UNIQUEIDENTIFIER NOT NULL,
    [UrdId] UNIQUEIDENTIFIER NOT NULL,
    [WstId] UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GdprWXR].[IX_GdprWXR_UrdId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprWXR_UrdId]
    ON [dbo].[GdprWXR]([UrdId] ASC);


GO
PRINT N'Creating [dbo].[GdprWXR].[IX_GdprWXR_WstId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprWXR_WstId]
    ON [dbo].[GdprWXR]([WstId] ASC);


GO
PRINT N'Creating [dbo].[DF_GdprCXP_Id]...';


GO
ALTER TABLE [dbo].[GdprCXP]
    ADD CONSTRAINT [DF_GdprCXP_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprCXP_ConsentCode]...';


GO
ALTER TABLE [dbo].[GdprCXP]
    ADD CONSTRAINT [DF_GdprCXP_ConsentCode] DEFAULT 0 FOR [ConsentCode];


GO
PRINT N'Creating [dbo].[DF_GdprCXP_Granted]...';


GO
ALTER TABLE [dbo].[GdprCXP]
    ADD CONSTRAINT [DF_GdprCXP_Granted] DEFAULT SYSUTCDATETIME() FOR [Granted];


GO
PRINT N'Creating [dbo].[DF_GdprDCD_Id]...';


GO
ALTER TABLE [dbo].[GdprDCD]
    ADD CONSTRAINT [DF_GdprDCD_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprDTD_Id]...';


GO
ALTER TABLE [dbo].[GdprDTD]
    ADD CONSTRAINT [DF_GdprDTD_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprDXP_Id]...';


GO
ALTER TABLE [dbo].[GdprDXP]
    ADD CONSTRAINT [DF_GdprDXP_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprDXP_ProcFlags]...';


GO
ALTER TABLE [dbo].[GdprDXP]
    ADD CONSTRAINT [DF_GdprDXP_ProcFlags] DEFAULT 0 FOR [ProcFlags];


GO
PRINT N'Creating [dbo].[DF_GdprEDT_Id]...';


GO
ALTER TABLE [dbo].[GdprEDT]
    ADD CONSTRAINT [DF_GdprEDT_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprEDT_TransferFlag]...';


GO
ALTER TABLE [dbo].[GdprEDT]
    ADD CONSTRAINT [DF_GdprEDT_TransferFlag] DEFAULT 0 FOR [TransferFlag];


GO
PRINT N'Creating [dbo].[DF_GdprFPD_Id]...';


GO
ALTER TABLE [dbo].[GdprFPD]
    ADD CONSTRAINT [DF_GdprFPD_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprFPD_ConsentCode]...';


GO
ALTER TABLE [dbo].[GdprFPD]
    ADD CONSTRAINT [DF_GdprFPD_ConsentCode] DEFAULT 0 FOR [ConsentCode];


GO
PRINT N'Creating [dbo].[DF_GdprFPD_Status]...';


GO
ALTER TABLE [dbo].[GdprFPD]
    ADD CONSTRAINT [DF_GdprFPD_Status] DEFAULT 0 FOR [Status];


GO
PRINT N'Creating [dbo].[DF_GdprFPD_ProcFlag]...';


GO
ALTER TABLE [dbo].[GdprFPD]
    ADD CONSTRAINT [DF_GdprFPD_ProcFlag] DEFAULT 0 FOR [ProcFlag];


GO
PRINT N'Creating [dbo].[DF_GdprPDF_Id]...';


GO
ALTER TABLE [dbo].[GdprPDF]
    ADD CONSTRAINT [DF_GdprPDF_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprPDF_Combine]...';


GO
ALTER TABLE [dbo].[GdprPDF]
    ADD CONSTRAINT [DF_GdprPDF_Combine] DEFAULT 0 FOR [Combine];


GO
PRINT N'Creating [dbo].[DF_GdprPDS_Id]...';


GO
ALTER TABLE [dbo].[GdprPDS]
    ADD CONSTRAINT [DF_GdprPDS_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprPDS_Status]...';


GO
ALTER TABLE [dbo].[GdprPDS]
    ADD CONSTRAINT [DF_GdprPDS_Status] DEFAULT 0 FOR [Status];


GO
PRINT N'Creating [dbo].[DF_GdprPDS_UserUpdateFlag]...';


GO
ALTER TABLE [dbo].[GdprPDS]
    ADD CONSTRAINT [DF_GdprPDS_UserUpdateFlag] DEFAULT 0 FOR [UserUpdateFlag];


GO
PRINT N'Creating [dbo].[DF_GdprPDS_Created]...';


GO
ALTER TABLE [dbo].[GdprPDS]
    ADD CONSTRAINT [DF_GdprPDS_Created] DEFAULT SYSUTCDATETIME() FOR [Created];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_Id]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_ChildFlag]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_ChildFlag] DEFAULT 0 FOR [ChildFlag];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_StopComms]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_StopComms] DEFAULT 0 FOR [StopComms];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_RestrictProc]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_RestrictProc] DEFAULT 0 FOR [RestrictProc];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_LoginCount]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_LoginCount] DEFAULT 0 FOR [LoginCount];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_UpdateFlag]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_UpdateFlag] DEFAULT 0 FOR [UpdateFlag];


GO
PRINT N'Creating [dbo].[DF_GdprRPD_Created]...';


GO
ALTER TABLE [dbo].[GdprRPD]
    ADD CONSTRAINT [DF_GdprRPD_Created] DEFAULT SYSUTCDATETIME() FOR [Created];


GO
PRINT N'Creating [dbo].[DF_GdprRXP_Id]...';


GO
ALTER TABLE [dbo].[GdprRXP]
    ADD CONSTRAINT [DF_GdprRXP_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprRXP_ProcFlags]...';


GO
ALTER TABLE [dbo].[GdprRXP]
    ADD CONSTRAINT [DF_GdprRXP_ProcFlags] DEFAULT 0 FOR [ProcFlags];


GO
PRINT N'Creating [dbo].[DF_GdprTest_Id]...';


GO
ALTER TABLE [dbo].[GdprTest]
    ADD CONSTRAINT [DF_GdprTest_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprTest_Created]...';


GO
ALTER TABLE [dbo].[GdprTest]
    ADD CONSTRAINT [DF_GdprTest_Created] DEFAULT SYSUTCDATETIME() FOR [Created];


GO
PRINT N'Creating [dbo].[DF_GdprURD_Id]...';


GO
ALTER TABLE [dbo].[GdprURD]
    ADD CONSTRAINT [DF_GdprURD_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprURP_RoleCode]...';


GO
ALTER TABLE [dbo].[GdprURD]
    ADD CONSTRAINT [DF_GdprURP_RoleCode] DEFAULT 0 FOR [RoleCode];


GO
PRINT N'Creating [dbo].[DF_GdprURP_Status]...';


GO
ALTER TABLE [dbo].[GdprURD]
    ADD CONSTRAINT [DF_GdprURP_Status] DEFAULT 0 FOR [Status];


GO
PRINT N'Creating [dbo].[DF_GdprUTA_Id]...';


GO
ALTER TABLE [dbo].[GdprUTA]
    ADD CONSTRAINT [DF_GdprUTA_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprUTA_Created]...';


GO
ALTER TABLE [dbo].[GdprUTA]
    ADD CONSTRAINT [DF_GdprUTA_Created] DEFAULT SYSUTCDATETIME() FOR [Accepted];


GO
PRINT N'Creating [dbo].[DF_GdprWST_Id]...';


GO
ALTER TABLE [dbo].[GdprWST]
    ADD CONSTRAINT [DF_GdprWST_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[DF_GdprWST_Created]...';


GO
ALTER TABLE [dbo].[GdprWST]
    ADD CONSTRAINT [DF_GdprWST_Created] DEFAULT SYSUTCDATETIME() FOR [Created];


GO
PRINT N'Creating [dbo].[DF_GdprWST_Status]...';


GO
ALTER TABLE [dbo].[GdprWST]
    ADD CONSTRAINT [DF_GdprWST_Status] DEFAULT 0 FOR [Status];


GO
PRINT N'Creating [dbo].[DF_GdprWXR_Id]...';


GO
ALTER TABLE [dbo].[GdprWXR]
    ADD CONSTRAINT [DF_GdprWXR_Id] DEFAULT NEWID() FOR [Id];


GO
PRINT N'Creating [dbo].[FK_GdprCXP_FpdId]...';


GO
ALTER TABLE [dbo].[GdprCXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprCXP_FpdId] FOREIGN KEY ([FpdId]) REFERENCES [dbo].[GdprFPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprCXP_RpdId]...';


GO
ALTER TABLE [dbo].[GdprCXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprCXP_RpdId] FOREIGN KEY ([RpdId]) REFERENCES [dbo].[GdprRPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprDXP_FpdId]...';


GO
ALTER TABLE [dbo].[GdprDXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprDXP_FpdId] FOREIGN KEY ([FpdId]) REFERENCES [dbo].[GdprFPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprDXP_PdsId]...';


GO
ALTER TABLE [dbo].[GdprDXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprDXP_PdsId] FOREIGN KEY ([PdsId]) REFERENCES [dbo].[GdprPDS] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprEDT_FpdId]...';


GO
ALTER TABLE [dbo].[GdprEDT] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprEDT_FpdId] FOREIGN KEY ([FpdId]) REFERENCES [dbo].[GdprFPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprPDS_DtdId]...';


GO
ALTER TABLE [dbo].[GdprPDS] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprPDS_DtdId] FOREIGN KEY ([DtdId]) REFERENCES [dbo].[GdprDTD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprPDS_DcdId]...';


GO
ALTER TABLE [dbo].[GdprPDS] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprPDS_DcdId] FOREIGN KEY ([DcdId]) REFERENCES [dbo].[GdprDCD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprRPD_UrdId]...';


GO
ALTER TABLE [dbo].[GdprRPD] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprRPD_UrdId] FOREIGN KEY ([UrdId]) REFERENCES [dbo].[GdprURD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprRXP_FpdId]...';


GO
ALTER TABLE [dbo].[GdprRXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprRXP_FpdId] FOREIGN KEY ([FpdId]) REFERENCES [dbo].[GdprFPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprRXP_UrdId]...';


GO
ALTER TABLE [dbo].[GdprRXP] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprRXP_UrdId] FOREIGN KEY ([UrdId]) REFERENCES [dbo].[GdprURD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprUTA_RpdId]...';


GO
ALTER TABLE [dbo].[GdprUTA] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprUTA_RpdId] FOREIGN KEY ([RpdId]) REFERENCES [dbo].[GdprRPD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprUTA_WstId]...';


GO
ALTER TABLE [dbo].[GdprUTA] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprUTA_WstId] FOREIGN KEY ([WstId]) REFERENCES [dbo].[GdprWST] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprWXR_UrdId]...';


GO
ALTER TABLE [dbo].[GdprWXR] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprWXR_UrdId] FOREIGN KEY ([UrdId]) REFERENCES [dbo].[GdprURD] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GdprWXR_WstId]...';


GO
ALTER TABLE [dbo].[GdprWXR] WITH NOCHECK
    ADD CONSTRAINT [FK_GdprWXR_WstId] FOREIGN KEY ([WstId]) REFERENCES [dbo].[GdprWST] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[GdprCXP] WITH CHECK CHECK CONSTRAINT [FK_GdprCXP_FpdId];

ALTER TABLE [dbo].[GdprCXP] WITH CHECK CHECK CONSTRAINT [FK_GdprCXP_RpdId];

ALTER TABLE [dbo].[GdprDXP] WITH CHECK CHECK CONSTRAINT [FK_GdprDXP_FpdId];

ALTER TABLE [dbo].[GdprDXP] WITH CHECK CHECK CONSTRAINT [FK_GdprDXP_PdsId];

ALTER TABLE [dbo].[GdprEDT] WITH CHECK CHECK CONSTRAINT [FK_GdprEDT_FpdId];

ALTER TABLE [dbo].[GdprPDS] WITH CHECK CHECK CONSTRAINT [FK_GdprPDS_DtdId];

ALTER TABLE [dbo].[GdprPDS] WITH CHECK CHECK CONSTRAINT [FK_GdprPDS_DcdId];

ALTER TABLE [dbo].[GdprRPD] WITH CHECK CHECK CONSTRAINT [FK_GdprRPD_UrdId];

ALTER TABLE [dbo].[GdprRXP] WITH CHECK CHECK CONSTRAINT [FK_GdprRXP_FpdId];

ALTER TABLE [dbo].[GdprRXP] WITH CHECK CHECK CONSTRAINT [FK_GdprRXP_UrdId];

ALTER TABLE [dbo].[GdprUTA] WITH CHECK CHECK CONSTRAINT [FK_GdprUTA_RpdId];

ALTER TABLE [dbo].[GdprUTA] WITH CHECK CHECK CONSTRAINT [FK_GdprUTA_WstId];

ALTER TABLE [dbo].[GdprWXR] WITH CHECK CHECK CONSTRAINT [FK_GdprWXR_UrdId];

ALTER TABLE [dbo].[GdprWXR] WITH CHECK CHECK CONSTRAINT [FK_GdprWXR_WstId];


GO
PRINT N'Update complete.';


GO
