CREATE TABLE [dbo].[GdprDTD]
(
    [Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprDTD_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [DisplayName] NVARCHAR(40) NOT NULL, 
    [Details] NVARCHAR(MAX) NULL
)
GO;

CREATE UNIQUE CLUSTERED INDEX [IX_GdprDTD_DisplayName] ON [dbo].[GdprDTD] ([DisplayName])
GO;
