CREATE TABLE [dbo].[GdprDXP]
(
    [Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprDXP_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [ProcFlags] INT CONSTRAINT [DF_GdprDXP_ProcFlags] DEFAULT 0 NOT NULL, 
    [FpdId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprDXP_FpdId] FOREIGN KEY REFERENCES [dbo].[GdprFPD] (Id) ON DELETE CASCADE  NOT NULL, 
    [PdsId] UNIQUEIDENTIFIER CONSTRAINT [FK_GdprDXP_PdsId] FOREIGN KEY REFERENCES [dbo].[GdprPDS] (Id) ON DELETE CASCADE  NOT NULL, 
)
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprDXP_FpdId] ON [dbo].[GdprDXP] ([FpdId])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprDXP_RpdId] ON [dbo].[GdprDXP] ([PdsId])
GO;
