CREATE TABLE [dbo].[GdprUTA]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT [DF_GdprUTA_Id] DEFAULT NEWID() NOT NULL PRIMARY KEY NONCLUSTERED, 
    [Accepted] DATETIME2 CONSTRAINT [DF_GdprUTA_Created] DEFAULT SYSUTCDATETIME() NOT NULL,  
    [Revoked] DATETIME2 NULL, 
    [RpdId] UNIQUEIDENTIFIER  CONSTRAINT [FK_GdprUTA_RpdId]  FOREIGN KEY REFERENCES [dbo].[GdprRPD] (Id) ON DELETE CASCADE  NOT NULL,  
    [WstId] UNIQUEIDENTIFIER  CONSTRAINT [FK_GdprUTA_WstId]  FOREIGN KEY REFERENCES [dbo].[GdprWST] (Id) ON DELETE CASCADE  NOT NULL, 
)
GO;
CREATE UNIQUE CLUSTERED INDEX [IX_GdprUTA_Created] ON [dbo].[GdprUTA] ([Accepted])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprUTA_RpdId] ON [dbo].[GdprUTA] ([RpdId])
GO;
CREATE UNIQUE NONCLUSTERED INDEX [IX_GdprUTA_WstId] ON [dbo].[GdprUTA] ([WstId])
GO;